name: distribute-arm

on:
  - workflow_dispatch

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: armv7
            distro: ubuntu20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build artifact
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}/src:/src"
          env: |
            artifact_name: Fritzbox-telegraf-plugin-${{ matrix.distro }}_${{matrix.arch }}
          shell: /bin/sh
          install: |
            echo "install"
          run: |
            echo "Produced artifact at ${PWD}/src/build/dist"
            touch "${PWD}/build/disk/test"
      - name: Show the artifact
        run: |
          ls -al "${PWD}/build/disk/test"
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-dist
      #     path: /artifacts/${artifact_name}
      #     retention-days: 7
