name: distribute-arm

on:
 - workflow_dispatch

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: aarch7
            distro: ubuntu20.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
      - name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: |
            artifact_name: Fritzbox-telegraf-plugin-${{ matrix.distro }}_${{matrix.arch }}
          shell: /bin/sh
          install: |
            echo "install"
          run: |
            echo "Produced artifact at /artifacts/${artifact_name}"
      - name: Show the artifact
        run: |
          ls -al "${PWD}/artifacts"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: /artifacts/${artifact_name}
          retention-days: 7
